security:
    access_decision_manager:
        strategy: unanimous
        allow_if_all_abstain: false

    encoders:
        App\Entity\User: bcrypt

    providers:
        db_user:
            id: App\Components\Users\Provider\UserProvider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
             anonymous: ~
             provider: db_user
             http_basic: ~
             form_login:
                 login_path: /login
                 check_path: /login
             logout:
                 path: /logout

            # activate different ways to authenticate

            # http_basic: true
            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: true
            # https://symfony.com/doc/current/security/form_login_setup.html

#    access_control:
#         - { path: ^/admin, roles: ROLE_ADMIN }
#         - { path: ^/profile, roles: ROLE_USER }