app_preview:
  path: /preview
  controller: App\Controller\DefaultController::preview

#page routers
page_list:
  path: /page
  controller:  App\Controller\PageController::list

page_add:
  path: /page/add
  controller:  App\Controller\PageController::add

page_view:
  path: /page/{id}
  controller:  App\Controller\PageController::view
  requirements:
    id: '\d+'

page_comments:
  path: /page/{id}/comments
  controller:  App\Controller\PageController::comments
  requirements:
    id: '\d+'

page_edit:
  path: /page/{id}/edit
  controller:  App\Controller\PageController::edit
  requirements:
    id: '\d+'

page_delete:
  path: /page/{id}/delete
  controller:  App\Controller\PageController::remove
  requirements:
    id: '\d+'

page_search:
  path: /search
  controller:  App\Controller\PageController::search

#term  routers
term_list:
  path: /term
  controller:  App\Controller\TermController::list

term_add:
  path: /term/add
  controller:  App\Controller\TermController::add

term_view:
  path: /term/{id}
  controller:  App\Controller\TermController::view
  requirements:
    id: '\d+'

term_edit:
  path: /term/{id}/edit
  controller:  App\Controller\TermController::edit
  requirements:
    id: '\d+'

term_delete:
  path: /term/{id}/delete
  controller:  App\Controller\TermController::delete
  requirements:
    id: '\d+'

#comments routers
comment_edit:
  path: /comment/{id}/edit
  controller:  App\Controller\CommentController::edit
  requirements:
    id: '\d+'

comment_delete:
  path: /comment/{id}/delete
  controller:  App\Controller\CommentController::remove
  requirements:
    id: '\d+'

#user routers
login:
  path: /login
  controller: App\Controller\SecurityController::login

logout:
  path: /logout

register:
  path: /register
  controller: App\Controller\UserController::register

recover:
  path: /recover/{token}
  controller: App\Controller\UserController::recover
  defaults:
          token: null

user:
  path: /user

user_password_recover:
  path: /user/recover-password
  controller: App\Controller\UserController::recoverPassword